[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/copier"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"
